name: Release Please
on:
    workflow_dispatch: {}
    push:
        branches:
            - main
jobs:
    release-please:
        env:
            RELEASE_PAT: ${{ secrets.RELEASE_PAT }}
        container:
            image: node:22-alpine
        steps:
            - uses: actions/checkout@v6
            - name: Run
              run: |-
                npx release-please release-pr --repo-url=${{ github.server_url }}/${{ github.repository }} --token=$RELEASE_PAT --release-type=go --pull-request-header=":robot: new release" --pull-request-footer=" "
                npx release-please github-release --repo-url=${{ github.server_url }}/${{ github.repository }} --token=$RELEASE_PAT --release-type=go
        runs-on: ubuntu-latest
